service:
  url:
    oauth2: http://localhost:8080
spring:
  application:
    name: proxy
  profiles:
    active: shared
  cloud:
    gateway:
      default-filters:
        - RemoveResponseHeader=Expires
        - RemoveResponseHeader=Pragma
        - DedupeResponseHeader=Cache-Control
      routes:
        - id: identityAccessModule
          uri: lb://oauth
          predicates:
            - Path=/auth-svc/**
          filters:
            - RewritePath=/auth-svc(?<segment>/?.*), $\{segment}
  security:
    oauth2:
      client:
        registration:
          manytree:
            client-id: 0C8AZYTQ5W5C
            client-secret: root
            authorization-grant-type: client_credentials
        provider:
          manytree:
            authorization-uri: ${service.url.oauth2}/authorize
            token-uri: ${service.url.oauth2}/oauth/token
            user-info-uri: ${service.url.oauth2}/userinfo
            user-name-attribute: sub
            jwk-set-uri: ${service.url.oauth2}/.well-known/jwks.json
      resourceserver:
        jwt:
          jwk-set-uri: ${service.url.oauth2}/.well-known/jwks.json


security:
  oauth2:
    client:
      clientSecret: root
      clientId: 0C8AZYTQ5W5C
url:
  endpoint: ${service.url.oauth2}/endpoints/root
ribbon:
  ReadTimeout: 15000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 35000
#security:
#  oauth2:
#    client:
#      clientId: 0C8AZYTQ5W5C
#      clientSecret: root
#      accessTokenUri: ${service.url.oauth2}/oauth/token
#    resource:
#      jwt:
#        key-uri: ${service.url.oauth2}/oauth/token_key
logbook:
  obfuscate:
    headers: Authorization,cookie
    parameters: access_token,password
  write:
    category: http.wire-log
    level: DEBUG
    max-body-size: 100
  exclude:
    - '**/v2/api-docs'
    - '**/swagger-ui.html'
    - '**/webjars/**'
    - '**/swagger-resources/**'
    - '**/csrf'
    - '**/'
    - '**/auth-svc/oauth/token'
logging:
  level:
    http:
      wire-log: DEBUG
    org:
      zalando:
        logbook: TRACE