-- *** manually insert below record if you running it in development mode for fist time***
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(1,'4','/auth-svc/clients/user','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''write'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(0,'4','/auth-svc/clients/root','GET','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(2,'4','/auth-svc/clients/root','POST','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(125,'4','/auth-svc/clients/root/**','GET','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(126,'4','/auth-svc/clients/root/**','PATCH','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(3,'4','/auth-svc/clients/root/**','PUT','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(4,'4','/auth-svc/clients/root/**','DELETE','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(5,'4','/auth-svc/users/public','POST','hasRole(''ROLE_FRONTEND'') and hasRole(''ROLE_FIRST_PARTY'') and #oauth2.hasScope(''write'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(6,'4','/auth-svc/users/admin','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(127,'4','/auth-svc/users/admin/**','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(7,'4','/auth-svc/users/admin/**','PUT','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(8,'4','/auth-svc/users/admin/**','DELETE','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(9,'4','/auth-svc/users/user/pwd','PUT','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(10,'4','/auth-svc/authorize','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(11,'4','/auth-svc/users/app','GET','hasRole(''ROLE_BACKEND'') and hasRole(''ROLE_FIRST_PARTY'') and #oauth2.hasScope(''read'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(12,'4','/auth-svc/pending-users/public','POST','hasRole(''ROLE_FRONTEND'') and hasRole(''ROLE_FIRST_PARTY'') and #oauth2.hasScope(''write'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(13,'4','/auth-svc/users/public/forgetPwd','POST','hasRole(''ROLE_FRONTEND'') and hasRole(''ROLE_FIRST_PARTY'') and #oauth2.hasScope(''write'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(14,'4','/auth-svc/users/public/resetPwd','POST','hasRole(''ROLE_FRONTEND'') and hasRole(''ROLE_FIRST_PARTY'') and #oauth2.hasScope(''write'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method) VALUES(15,'4','/auth-svc/oauth/token','POST');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(16,'11','/proxy/revoke-tokens/root','POST','(hasRole(''ROLE_ROOT'')) and #oauth2.hasScope(''trust'')');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(17,'11','/proxy/revoke-tokens/admin','POST','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'')');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(129,'11','/proxy/revoke-tokens/app','POST','hasRole(''ROLE_BACKEND'') and #oauth2.hasScope(''trust'')');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(18,'11','/proxy/endpoints/root','POST','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'')');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(19,'11','/proxy/endpoints/root','GET','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'')');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(128,'11','/proxy/endpoints/root/**','GET','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'')');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(20,'11','/proxy/endpoints/root/**','PUT','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'')');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(21,'11','/proxy/endpoints/root/**','DELETE','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'')');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(23,'15','/profile-svc/profiles/search','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(24,'15','/profile-svc/profiles','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(25,'15','/profile-svc/profiles/**/addresses','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(26,'15','/profile-svc/profiles/**/addresses/**','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(27,'15','/profile-svc/profiles/**/addresses','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(28,'15','/profile-svc/profiles/**/addresses/**','PUT','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(29,'15','/profile-svc/profiles/**/addresses/**','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(30,'15','/profile-svc/profiles/**/orders/**/confirm','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(31,'15','/profile-svc/profiles/**/orders','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(32,'15','/profile-svc/profiles/**/orders/**','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(33,'15','/profile-svc/profiles/**/orders/**','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(34,'15','/profile-svc/profiles/**/orders/**','PUT','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(35,'15','/profile-svc/profiles/**/orders/**','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(36,'15','/profile-svc/profiles/**/cart','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(37,'15','/profile-svc/profiles/**/cart','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(38,'15','/profile-svc/profiles/**/cart/**','PUT','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(39,'15','/profile-svc/profiles/**/cart/**','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(40,'15','/profile-svc/orders','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(41,'15','/profile-svc/profiles/**/orders/**/replace','PUT','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(57,'17','/messenger-svc/notifyBy/email/newOrder','POST','hasRole(''ROLE_BACKEND'') and hasRole(''ROLE_FIRST_PARTY'') and #oauth2.hasScope(''trust'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(58,'17','/messenger-svc/notifyBy/email/activationCode','POST','hasRole(''ROLE_BACKEND'') and hasRole(''ROLE_FIRST_PARTY'') and #oauth2.hasScope(''trust'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(59,'17','/messenger-svc/notifyBy/email/pwdReset','POST','hasRole(''ROLE_BACKEND'') and hasRole(''ROLE_FIRST_PARTY'') and #oauth2.hasScope(''trust'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(60,'18','/file-upload-svc/files','POST','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.hasScope(''write'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method) VALUES(61,'18','/file-upload-svc/files/**','GET');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(62,'19','/payment-svc/paymentLink','POST','hasRole(''ROLE_BACKEND'') and #oauth2.hasScope(''trust'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(63,'19','/payment-svc/paymentStatus/**','GET','hasRole(''ROLE_BACKEND'') and #oauth2.hasScope(''trust'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(65,'21','/bbs-svc/private/comments','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method) VALUES(66,'21','/bbs-svc/public/posts/**/comments','GET');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(67,'21','/bbs-svc/private/posts/**/comments','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(68,'21','/bbs-svc/private/comments/**','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method) VALUES(69,'21','/bbs-svc/public/posts','GET');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(70,'21','/bbs-svc/private/posts','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(71,'21','/bbs-svc/private/posts','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method) VALUES(72,'21','/bbs-svc/public/posts/**','GET');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(73,'21','/bbs-svc/private/posts/**','PUT','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(74,'21','/bbs-svc/private/posts/**','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(75,'21','/bbs-svc/private/posts/**/likes','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(76,'21','/bbs-svc/private/posts/**/likes','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(77,'21','/bbs-svc/private/comments/**/likes','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(78,'21','/bbs-svc/private/comments/**/likes','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(79,'21','/bbs-svc/private/posts/**/dislikes','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(80,'21','/bbs-svc/private/posts/**/dislikes','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(81,'21','/bbs-svc/private/comments/**/dislikes','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(82,'21','/bbs-svc/private/comments/**/dislikes','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(83,'21','/bbs-svc/private/posts/**/reports','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(84,'21','/bbs-svc/private/posts/**/reports','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(85,'21','/bbs-svc/private/comments/**/reports','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(86,'21','/bbs-svc/private/comments/**/reports','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(87,'21','/bbs-svc/private/posts/**/notInterested','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(88,'21','/bbs-svc/private/posts/**/notInterested','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(89,'21','/bbs-svc/private/comments/**/notInterested','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(90,'21','/bbs-svc/private/comments/**/notInterested','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(91,'21','/bbs-svc/admin/posts','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(92,'21','/bbs-svc/admin/posts/**','DELETE','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(93,'21','/bbs-svc/admin/comments','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(94,'21','/bbs-svc/admin/comments/**','DELETE','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(95,'21','/bbs-svc/admin/likes','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(96,'21','/bbs-svc/admin/dislikes','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(97,'21','/bbs-svc/admin/reports','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(98,'21','/bbs-svc/admin/notInterested','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(99,'15','/profile-svc/profiles/orders/id','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(100,'15','/profile-svc/profiles/orders/scheduler/resubmit','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(42,'16','/product-svc/catalogs/admin','POST','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(43,'16','/product-svc/catalogs/admin/**','PUT','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(44,'16','/product-svc/catalogs/admin/**','DELETE','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method) VALUES(114,'16','/product-svc/filters/public','GET');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(101,'16','/product-svc/catalogs/admin','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(105,'16','/product-svc/attributes/admin','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(106,'16','/product-svc/attributes/admin','POST','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(107,'16','/product-svc/attributes/admin/**','PUT','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(108,'16','/product-svc/attributes/admin/**','DELETE','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(109,'16','/product-svc/filters/admin','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(110,'16','/product-svc/filters/admin/**','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(111,'16','/product-svc/filters/admin','POST','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(112,'16','/product-svc/filters/admin/**','PUT','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method) VALUES(53,'16','/product-svc/catalogs/public','GET');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(113,'16','/product-svc/filters/admin/**','DELETE','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(116,'16','/product-svc/attributes/admin/**','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(117,'16','/product-svc/catalogs/admin/**','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method) VALUES(54,'16','/product-svc/products/public','GET');
INSERT INTO biz_endpoint (ID,resource_Id,path,method) VALUES(55,'16','/product-svc/products/public/**','GET');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(103,'16','/product-svc/products/admin','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(47,'16','/product-svc/products/admin','POST','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(119,'16','/product-svc/products/admin','PATCH','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(120,'16','/product-svc/products/admin','DELETE','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(52,'16','/product-svc/products/admin/**','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(48,'16','/product-svc/products/admin/**','PUT','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(118,'16','/product-svc/products/admin/**','PATCH','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(49,'16','/product-svc/products/admin/**','DELETE','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(121,'16','/product-svc/products/app','GET','hasRole(''ROLE_BACKEND'') and #oauth2.hasScope(''trust'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(46,'16','/product-svc/products/app','PATCH','hasRole(''ROLE_BACKEND'') and #oauth2.hasScope(''trust'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(122,'16','/product-svc/products/change/app/**','DELETE','hasRole(''ROLE_BACKEND'') and #oauth2.hasScope(''trust'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(123,'16','/product-svc/attributes/admin/**','PATCH','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(124,'16','/product-svc/catalogs/admin/**','PATCH','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
