-- *** manually insert below record if you running it in development mode for fist time***
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(1,'oauth2-id','/auth-svc/clients/user','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''write'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(0,'oauth2-id','/auth-svc/clients/root','GET','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(2,'oauth2-id','/auth-svc/clients/root','POST','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(125,'oauth2-id','/auth-svc/clients/root/**','GET','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(126,'oauth2-id','/auth-svc/clients/root/**','PATCH','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(3,'oauth2-id','/auth-svc/clients/root/**','PUT','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(4,'oauth2-id','/auth-svc/clients/root/**','DELETE','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(5,'oauth2-id','/auth-svc/users/public','POST','hasRole(''ROLE_FRONTEND'') and hasRole(''ROLE_FIRST_PARTY'') and #oauth2.hasScope(''write'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(6,'oauth2-id','/auth-svc/users/admin','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(127,'oauth2-id','/auth-svc/users/admin/**','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(7,'oauth2-id','/auth-svc/users/admin/**','PUT','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(8,'oauth2-id','/auth-svc/users/admin/**','DELETE','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(9,'oauth2-id','/auth-svc/users/user/pwd','PUT','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(10,'oauth2-id','/auth-svc/authorize','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(11,'oauth2-id','/auth-svc/users/app','GET','hasRole(''ROLE_BACKEND'') and hasRole(''ROLE_FIRST_PARTY'') and #oauth2.hasScope(''read'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(12,'oauth2-id','/auth-svc/pending-users/public','POST','hasRole(''ROLE_FRONTEND'') and hasRole(''ROLE_FIRST_PARTY'') and #oauth2.hasScope(''write'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(13,'oauth2-id','/auth-svc/users/public/forgetPwd','POST','hasRole(''ROLE_FRONTEND'') and hasRole(''ROLE_FIRST_PARTY'') and #oauth2.hasScope(''write'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(14,'oauth2-id','/auth-svc/users/public/resetPwd','POST','hasRole(''ROLE_FRONTEND'') and hasRole(''ROLE_FIRST_PARTY'') and #oauth2.hasScope(''write'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method) VALUES(15,'oauth2-id','/auth-svc/oauth/token','POST');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(16,'edge-proxy','/proxy/blacklist/client','POST','(hasRole(''ROLE_ROOT'')) and #oauth2.hasScope(''trust'')');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(17,'edge-proxy','/proxy/blacklist/resourceOwner','POST','(hasRole(''ROLE_ADMIN'') or hasRole(''ROLE_ROOT'')) and #oauth2.hasScope(''trust'')');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(18,'edge-proxy','/proxy/endpoints','POST','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'')');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(19,'edge-proxy','/proxy/endpoints','GET','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'')');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(20,'edge-proxy','/proxy/endpoints/**','GET','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'')');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(20,'edge-proxy','/proxy/endpoints/**','PUT','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'')');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(21,'edge-proxy','/proxy/endpoints/**','DELETE','hasRole(''ROLE_ROOT'') and #oauth2.hasScope(''trust'')');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(23,'user-profile','/profile-svc/profiles/search','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(24,'user-profile','/profile-svc/profiles','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(25,'user-profile','/profile-svc/profiles/**/addresses','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(26,'user-profile','/profile-svc/profiles/**/addresses/**','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(27,'user-profile','/profile-svc/profiles/**/addresses','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(28,'user-profile','/profile-svc/profiles/**/addresses/**','PUT','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(29,'user-profile','/profile-svc/profiles/**/addresses/**','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(30,'user-profile','/profile-svc/profiles/**/orders/**/confirm','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(31,'user-profile','/profile-svc/profiles/**/orders','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(32,'user-profile','/profile-svc/profiles/**/orders/**','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(33,'user-profile','/profile-svc/profiles/**/orders/**','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(34,'user-profile','/profile-svc/profiles/**/orders/**','PUT','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(35,'user-profile','/profile-svc/profiles/**/orders/**','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(36,'user-profile','/profile-svc/profiles/**/cart','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(37,'user-profile','/profile-svc/profiles/**/cart','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(38,'user-profile','/profile-svc/profiles/**/cart/**','PUT','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(39,'user-profile','/profile-svc/profiles/**/cart/**','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(40,'user-profile','/profile-svc/orders','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(41,'user-profile','/profile-svc/profiles/**/orders/**/replace','PUT','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(57,'messenger','/messenger-svc/notifyBy/email/newOrder','POST','hasRole(''ROLE_BACKEND'') and hasRole(''ROLE_FIRST_PARTY'') and #oauth2.hasScope(''trust'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(58,'messenger','/messenger-svc/notifyBy/email/activationCode','POST','hasRole(''ROLE_BACKEND'') and hasRole(''ROLE_FIRST_PARTY'') and #oauth2.hasScope(''trust'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(59,'messenger','/messenger-svc/notifyBy/email/pwdReset','POST','hasRole(''ROLE_BACKEND'') and hasRole(''ROLE_FIRST_PARTY'') and #oauth2.hasScope(''trust'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(60,'file-upload','/file-upload-svc/files','POST','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.hasScope(''write'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method) VALUES(61,'file-upload','/file-upload-svc/files/**','GET');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(62,'payment','/payment-svc/paymentLink','POST','hasRole(''ROLE_BACKEND'') and #oauth2.hasScope(''trust'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(63,'payment','/payment-svc/paymentStatus/**','GET','hasRole(''ROLE_BACKEND'') and #oauth2.hasScope(''trust'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(65,'bbs','/bbs-svc/private/comments','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method) VALUES(66,'bbs','/bbs-svc/public/posts/**/comments','GET');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(67,'bbs','/bbs-svc/private/posts/**/comments','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(68,'bbs','/bbs-svc/private/comments/**','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method) VALUES(69,'bbs','/bbs-svc/public/posts','GET');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(70,'bbs','/bbs-svc/private/posts','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(71,'bbs','/bbs-svc/private/posts','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method) VALUES(72,'bbs','/bbs-svc/public/posts/**','GET');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(73,'bbs','/bbs-svc/private/posts/**','PUT','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(74,'bbs','/bbs-svc/private/posts/**','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(75,'bbs','/bbs-svc/private/posts/**/likes','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(76,'bbs','/bbs-svc/private/posts/**/likes','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(77,'bbs','/bbs-svc/private/comments/**/likes','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(78,'bbs','/bbs-svc/private/comments/**/likes','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(79,'bbs','/bbs-svc/private/posts/**/dislikes','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(80,'bbs','/bbs-svc/private/posts/**/dislikes','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(81,'bbs','/bbs-svc/private/comments/**/dislikes','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(82,'bbs','/bbs-svc/private/comments/**/dislikes','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(83,'bbs','/bbs-svc/private/posts/**/reports','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(84,'bbs','/bbs-svc/private/posts/**/reports','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(85,'bbs','/bbs-svc/private/comments/**/reports','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(86,'bbs','/bbs-svc/private/comments/**/reports','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(87,'bbs','/bbs-svc/private/posts/**/notInterested','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(88,'bbs','/bbs-svc/private/posts/**/notInterested','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(89,'bbs','/bbs-svc/private/comments/**/notInterested','POST','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(90,'bbs','/bbs-svc/private/comments/**/notInterested','DELETE','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(91,'bbs','/bbs-svc/admin/posts','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(92,'bbs','/bbs-svc/admin/posts/**','DELETE','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(93,'bbs','/bbs-svc/admin/comments','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(94,'bbs','/bbs-svc/admin/comments/**','DELETE','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(95,'bbs','/bbs-svc/admin/likes','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(96,'bbs','/bbs-svc/admin/dislikes','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(97,'bbs','/bbs-svc/admin/reports','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(98,'bbs','/bbs-svc/admin/notInterested','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(99,'user-profile','/profile-svc/profiles/orders/id','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(100,'user-profile','/profile-svc/profiles/orders/scheduler/resubmit','GET','hasRole(''ROLE_USER'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(42,'product','/product-svc/catalogs/admin','POST','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(43,'product','/product-svc/catalogs/admin/**','PUT','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(44,'product','/product-svc/catalogs/admin/**','DELETE','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method) VALUES(114,'product','/product-svc/filters/public','GET');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(101,'product','/product-svc/catalogs/admin','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(105,'product','/product-svc/attributes/admin','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(106,'product','/product-svc/attributes/admin','POST','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(107,'product','/product-svc/attributes/admin/**','PUT','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(108,'product','/product-svc/attributes/admin/**','DELETE','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(109,'product','/product-svc/filters/admin','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(110,'product','/product-svc/filters/admin/**','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(111,'product','/product-svc/filters/admin','POST','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(112,'product','/product-svc/filters/admin/**','PUT','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method) VALUES(53,'product','/product-svc/catalogs/public','GET');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(113,'product','/product-svc/filters/admin/**','DELETE','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(116,'product','/product-svc/attributes/admin/**','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(117,'product','/product-svc/catalogs/admin/**','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method) VALUES(54,'product','/product-svc/products/public','GET');
INSERT INTO biz_endpoint (ID,resource_Id,path,method) VALUES(55,'product','/product-svc/products/public/**','GET');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(103,'product','/product-svc/products/admin','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(47,'product','/product-svc/products/admin','POST','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(119,'product','/product-svc/products/admin','PATCH','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(120,'product','/product-svc/products/admin','DELETE','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(52,'product','/product-svc/products/admin/**','GET','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(48,'product','/product-svc/products/admin/**','PUT','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(118,'product','/product-svc/products/admin/**','PATCH','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(49,'product','/product-svc/products/admin/**','DELETE','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(121,'product','/product-svc/products/app','GET','hasRole(''ROLE_BACKEND'') and #oauth2.hasScope(''trust'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(46,'product','/product-svc/products/app','PATCH','hasRole(''ROLE_BACKEND'') and #oauth2.hasScope(''trust'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(122,'product','/product-svc/products/change/app/**','DELETE','hasRole(''ROLE_BACKEND'') and #oauth2.hasScope(''trust'') and #oauth2.isClient()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(123,'product','/product-svc/attributes/admin/**','PATCH','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
INSERT INTO biz_endpoint (ID,resource_Id,path,method,expression) VALUES(124,'product','/product-svc/catalogs/admin/**','PATCH','hasRole(''ROLE_ADMIN'') and #oauth2.hasScope(''trust'') and #oauth2.isUser()');
